# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build stage
FROM oven/bun:latest as builder

WORKDIR /app

# Install dependencies
COPY package.json bun.lockb ./
RUN bun install

# Copy source code
COPY . .

# Build the TypeScript files
RUN bun run build

# Stage 2: Production stage
FROM node:16-alpine

WORKDIR /app

# Copy the built files from the builder
COPY --from=builder /app/dist /app/dist
COPY package.json .

# Install only production dependencies
RUN npm install --omit=dev

# Command to run the MCP server
ENTRYPOINT ["node", "dist/main.js"]